version: "3.9"
services:
  mongo:
    build:
#      context: mongoDb
      dockerfile: mongoDb/Dockerfile
    restart: always
    ports:
      - 27018:27017
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: { }
